### ISSUE TITLE
xAOD migration: Truth

### ISSUE THREAD

**Issue by amete** [susynt/SusyCommon#43]
Hi guys,

So we've discussed this via e-mail before, but I wanted to move it here. For the truth xAOD, what do we plan to do? Do we want to process these and make SusyNt (Truth) that'll enable us to run over our existing code (which I think makes sense to me), or do we want to have truth xAOD => another simple format or direct results? Any ideas @dantrim @gerbaudo @suneetu @ataffard 

-s

**Comment by dantrim** [comment]
I am unfamiliar with NTUP_TRUTH (and newer formats). If we are making a separate version of susyNt, would we still plan to store the base information that we do now (4vector info, pdg, motherpdg)?

**Comment by ataffard** [comment]
I think we want to be able to do 2 things.

- run on xAOD truth and save only truth information to do acceptance studies or generator uncertainties studies. All other reco info should be dropped to keep the size really small.
Truth info is saved in TruthMet, TruthJet, TruthParticle (see SusyNt.h)

- when we run on xAOD, we need to save some truth information so that we can calculate the efficiency wrt to the truth selection and make the plot needed for hep-data.
   Here I am not sure what would be the difference between the truth info available compare to xAODTruth. Ideally, for all the reco object match to truth, we should have the truthX equivalent (where we doing this before?)

**Comment by gerbaudo** [comment]
Note to self: this is the issue discussed with @ataffard this morning.
We need to check that the pieces of truth info we store are sufficient
determine the selection/acceptance needed for the hepdata.
